// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZEnQv-dTJfxItHXr8SRNga6T0Lbc-11g',
    appId: '1:952229927180:web:d0a44897b103175d9b5129',
    messagingSenderId: '952229927180',
    projectId: 'fischerliste-7d23c',
    authDomain: 'fischerliste-7d23c.firebaseapp.com',
    databaseURL: 'https://fischerliste-7d23c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fischerliste-7d23c.appspot.com',
    measurementId: 'G-QZKT050SXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIqpBC1QIlta9l3-WBzgzJLCXx_FSdyW8',
    appId: '1:952229927180:android:27cebecd1fab2e7d9b5129',
    messagingSenderId: '952229927180',
    projectId: 'fischerliste-7d23c',
    databaseURL: 'https://fischerliste-7d23c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fischerliste-7d23c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy2V_-0qxpFuBbiF7Zm10b7YX7WG1JRtU',
    appId: '1:952229927180:ios:75d36e03445672ad9b5129',
    messagingSenderId: '952229927180',
    projectId: 'fischerliste-7d23c',
    databaseURL: 'https://fischerliste-7d23c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fischerliste-7d23c.appspot.com',
    iosClientId: '952229927180-1693mfgvq8u3o2uvol0k5besbsslj1bo.apps.googleusercontent.com',
    iosBundleId: 'com.fischerliste.fischerliste',
  );
}
